SELECT table_name
FROM all_tables
WHERE owner = 'HOTEL_ADMIN'; 

GRANT SELECT, INSERT, UPDATE, DELETE ON HOTEL_ADMIN.SEASONS TO HOTEL_APP;

SELECT OWNER, TABLE_NAME, PRIVILEGE
FROM DBA_TAB_PRIVS
WHERE GRANTEE = 'HOTEL_APP'
  AND OWNER = 'HOTEL_ADMIN'
  AND PRIVILEGE IN ('SELECT', 'INSERT', 'UPDATE', 'DELETE')
ORDER BY TABLE_NAME, PRIVILEGE;



-- SELECT TABLE_NAME
-- FROM ALL_TABLES
-- WHERE OWNER = 'HOTEL_ADMIN'
-- AND TABLE_NAME = 'SEASONS';


-- SELECT TABLE_SCHEMA, TABLE_NAME
-- FROM ALL_TAB_PRIVS
-- WHERE GRANTEE = 'HOTEL_APP' 
-- AND PRIVILEGE IN ('INSERT', 'UPDATE', 'SELECT', 'DELETE');