services:
  db:
    build: .
    container_name: postgres-cinema-container
    environment:
      POSTGRES_DB: cinema
      POSTGRES_USER: utilisateur
      POSTGRES_PASSWORD: motdepasse
    ports:
      - "5431:5431"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgwal:/var/lib/postgresql/wal
      - backups:/backups

volumes:
  pgdata:
  pgwal:
  backups: