


CREATE TABLE roles (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL UNIQUE
);

INSERT INTO roles (name) VALUES ('admin');
INSERT INTO roles (name) VALUES ('user');

CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    role_id NUMBER REFERENCES roles(id) NOT NULL DEFAULT 2 ON DELETE SET DEFAULT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP,
    is_email_verified BOOLEAN DEFAULT FALSE
);

CREATE TABLE freqeuency (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL UNIQUE
);

INSERT INTO frequency (name) VALUES ('once');
INSERT INTO frequency (name) VALUES ('daily');
INSERT INTO frequency (name) VALUES ('weekly');
INSERT INTO frequency (name) VALUES ('monthly');
INSERT INTO frequency (name) VALUES ('yearly');


-- INTERNATIONALISATION

CREATE TABLE nationalite (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL UNIQUE
);


CREATE TABLE translations (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lang_code_id VARCHAR2(2) UNIQUE NOT NULL,
    key VARCHAR2(255) UNIQUE NOT NULL,
    translations CLOB NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);




CREATE TABLE user_profiles (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES users(id) NOT NULL ON DELETE CASCADE,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    nationalite_id NUMBER REFERENCES nationalite(id) NOT NULL ON DELETE SET NULL,
    preferred_language_id NUMBER REFERENCES nationalite(id) NOT NULL ON DELETE SET NULL,
    accepts_marketing BOOLEAN DEFAULT TRUE,
    first_stay_remembered BOOLEAN,
    first_stay_date DATE CHECK (first_stay_date >= '1960-01-01' OR first_stay_date IS NULL),
    stay_frequency NUMBER REFERENCES frequency(id) DEFAULT 1 ON DELETE SET NULL,
)

CREATE TABLE newsletters (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR2(50) DEFAULT 'subscribed' CHECK (status IN ('subscribed', 'unsubscribed', 'bounced'))
);

-- gerer le lien entre newsletter et user via une vue




