services:
  oracle-db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oracle-database
    ports:
      - "1522:1521"
      - "5501:5500"
    environment:
      ORACLE_PWD: "YourPassword123"
      ORACLE_ENABLE_XDB: "true"
    volumes:
      - db_data:/opt/oracle/oradata

volumes:
  db_data:
